import "./globals.css";
import { Inter } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import { TasksProvider } from "../app/TaskContext";
import { Toaster } from "sonner";
import {AuthProvider} from './Providers'
import { PrimeReactProvider } from 'primereact/api';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: 'Task Manager',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-white`}>
        <AuthProvider>
          <PrimeReactProvider>
            <TasksProvider>
                <Toaster richColors />
                <NextTopLoader showSpinner={false} color="#6e9fff" />
                {children}
            </TasksProvider>
          </PrimeReactProvider>
        </AuthProvider> 
      </body>
    </html>
  );
}
